### ISSUE TITLE
build的时候会出错

### ISSUE THREAD

**Issue by hedge-hog** [ayaseruri/tongnews#1]
> Error:Could not find andy.ayaseruri.circularrevealactivitylib:lib:1.0.1.
> Required by:
> tongnews:app:unspecified

**Comment by ayaseruri** [comment]
可能是Gradle同步时候的网络问题，我正在检查。

**Comment by ayaseruri** [comment]
已经修复了，是我自己的jcenter上面两个库的包名问题。如果有其他问题请继续联系我:-D

**Comment by hedge-hog** [comment]
试了一下还是不行
>  Error:Could not find andy.ayaseruri.tagsviewlib:tagsviewlib:1.0.3.
> Required by:
>     tongnews:app:unspecified
> <a href="searchInBuildFiles">Search in build.gradle files</a>

在别人电脑上试了下，也是同样的的错误

**Comment by ayaseruri** [comment]
我这里重新clone一份编译是正常的，当然我的android studio挂翻墙代理，让同事的电脑也试验了一下，他也有这个问题，不过他的没有翻墙。我暂时也不知道为什么%>_<%
如果你那边仍有问题，出问题的那个库也是我写的，地址在https://github.com/ayaseruri/TagsView，你可以除去gradle依赖手动添加上面这个库到本项目之中。这样应该会成功的，你再试一试有问题可以联系我。

**Comment by hedge-hog** [comment]
我们也是直接路由器翻墙的
我试试手动的吧
谢谢解答
